spring:
  profile:
    active: local
  application:
    name: url-shortener
  url: localhost
  data:
    mongodb:
      database: ShortUrl
      url: mongodb+srv://aditya-sawant:S10dulkar@shorturl.hwzsv.mongodb.net/?retryWrites=true&w=majority&appName=ShortUrl
      ssl:
        enabled: true
eureka:
  client:
    hostname: localhost
    service-url:
      defaultZone: http://${eureka.client.hostname}:8001/eureka
  instance:
    lease-renewal-interval-in-seconds: 10 #send heartbeat every 10 seconds
    lease-expiration-duration-in-seconds: 30 #instance will be marked as unresponsive after 30 seconds
tinyurl:
  api:
    url: http://${spring.url}:${server.port}/
server:
  port: 8082
