spring:
  profile:
    active: local
  application:
    name: tinyurl-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#      routes:
#        id: user-service
#        uri: lb://user-service
#        predicates:
#          - Path=/users/register

server:
  port: 8000
eureka:
  client:
    hostname: localhost
    service-url:
      defaultZone: http://${eureka.client.hostname}:8001/eureka
  instance:
#    lease-renewal-interval-in-seconds: 10 #send heartbeat every 10 seconds
#    lease-expiration-duration-in-seconds: 30 #instance will be marked as unresponsive after 30 seconds
