spring:
  profile:
    active: local
  application:
    name: discovery-service
tinyurl:
  api:
    url: "www.tinyurl.com"
server:
  port: 8001
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    hostname: localhost
    service-url:
      defaultZone: http://${eureka.client.hostname}:${server.port}/eureka
#  server:
#    enable-self-preservation: false
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
